### PR TITLE
(#159) Handle exceptions raised in `retrieveWizardContextBasedOnUserChoice`

### LINKED ISSUE #159: Handle exceptions raised in `retrieveWizardContextBasedOnUserChoice`
Currently, there are errors in the `retrieveWizardContextBasedOnUserChoice` function:
```
java.lang.IllegalStateException: Unable to find credentials with "eTB1bmczcl9naXRodWIuY29t" identifier
	at me.fornever.todosaurus.core.issues.ToDoService.retrieveWizardContextBasedOnUserChoice(ToDoService.kt:174)
	at me.fornever.todosaurus.core.issues.ToDoService.access$retrieveWizardContextBasedOnUserChoice(ToDoService.kt:30)
	at me.fornever.todosaurus.core.issues.ToDoService$createNewIssue$1.invokeSuspend(ToDoService.kt:43)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:104)
	at kotlinx.coroutines.internal.SoftLimitedDispatcher$Worker.run(SoftLimitedDispatcher.kt:125)
	at kotlinx.coroutines.scheduling.TaskImpl.run(Tasks.kt:99)
	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:608)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:873)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:763)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:750)
```

It is necessary to display an error to the user and offer to forget his previous choice. I propose two `AnAction`'s to implement:
1. `Forget` which just forgets previous user's choice
2. `Forget and try again` which forgets previous user choice and then reopens the dialog to create a new issue

See the code near this line:
https://github.com/ForNeVeR/Todosaurus/blob/07c3a78b25f0a80d4eb958614204f7f42217556e/core/src/main/kotlin/me/fornever/todosaurus/core/issues/ToDoService.kt#L162

### PR DESCRIPTION
**Pull request by y0ung3r**
Will close #159

### CODE REVIEW

File: core/src/main/resources/messages/TodosaurusCore.properties [hunk 1]
```diff
@@ -5,6 +5,8 @@
 action.CreateNewIssue.text=Create New Issue
 action.OpenReportedIssueInBrowser.text=Open Issue In Browser
 action.OpenNewIssueInBrowser.text=Open in Browser
+action.ForgetChoiceAndTryAgainAction.text=Forget Choice And Try Again
+action.ForgetChoice.text=Forget Choice
```
Comment (ForNeVeR) [inline core/src/main/resources/messages/TodosaurusCore.properties:9]: _(Minor)_ I am starting to think that "Forget choice" is a confusing name for an action.

Imagine that you are reporting an issue, see an error, and is suddenly presented by an option to "forget choice", while you didn't do any choice in the current IDE session, and, ironically, might even forget about doing it previously.

Let's maybe name this "Choose another account", "Choose another tracker", or something alike?

File: core/src/main/kotlin/me/fornever/todosaurus/core/issues/ToDoService.kt [hunk 2]
```diff
@@ -41,7 +41,12 @@ class ToDoService(private val project: Project, private val scope: CoroutineScop
                 .getChoiceOrNull()
 
             if (savedChoice != null) {
-                val model = retrieveWizardContextBasedOnUserChoice(toDoItem, savedChoice)
+                val model = try {
+                    retrieveWizardContextBasedOnUserChoice(toDoItem, savedChoice)
+                }
+                catch (exception: Exception) {
+                    return@launch Notifications.Memoization.failed(exception, toDoItem, project)
+                }
```
Comment (ForNeVeR) [inline core/src/main/kotlin/me/fornever/todosaurus/core/issues/ToDoService.kt:49]: There are two issues with this block.

1. Almost any block is expected to pass-through cancellation exceptions.
2. In JVM, you better catch `Throwable` and not just `Exception`.

So let's rewrite this as
```
catch (t: Throwable) {
  if (t is CancellationException) throw t
  return@launch Notifications.Memoization.failed(exception, toDoItem, project)
}
```

**Review by ForNeVeR — CHANGES_REQUESTED** [review]

File: core/src/main/kotlin/me/fornever/todosaurus/core/issues/ToDoService.kt (hunk 2 above)
Comment (y0ung3r) [reply core/src/main/kotlin/me/fornever/todosaurus/core/issues/ToDoService.kt:49]: Am I understanding correctly that we will need to rewrite all `try-catch` blocks in `Todosaurus` using `Throwable`?

File: core/src/main/resources/messages/TodosaurusCore.properties (hunk 1 above)
Comment (y0ung3r) [reply core/src/main/resources/messages/TodosaurusCore.properties:9]: I agree. I'll fix it.

File: core/src/main/kotlin/me/fornever/todosaurus/core/issues/ToDoService.kt (hunk 2 above)
Comment (ForNeVeR) [reply core/src/main/kotlin/me/fornever/todosaurus/core/issues/ToDoService.kt:49]: Yep, preferably. But don't forget about cancellation.

File: core/src/main/resources/messages/TodosaurusCore.properties (hunk 1 above)
Comment (y0ung3r) [reply core/src/main/resources/messages/TodosaurusCore.properties]: So far I have replaced the text in these actions. 
Do I need to replace “Forget choice” with the new wording in Wizard? 
image

And in the settings?
image

Comment (ForNeVeR) [reply core/src/main/resources/messages/TodosaurusCore.properties]: I'd say yes for both cases. Let's have it "Clear saved data" in settings, and "Choose another tracker" (since we restart from the tracker step) in the wizard.

**Review by ForNeVeR — APPROVED** [review]
Thanks!
